### ISSUE TITLE
demo code of solo12 doesn't work

### ISSUE THREAD

**Issue by SiyuChen1** [machines-in-motion/reactive_planners#19]
Hello,

I tried to run the demo code of solo12 `src/reactive_planners/demos/demo_dgh_sim_solo12_step_adjustment.py`, but I found that it doesn't work. 

The error message is 
```
Traceback (most recent call last):
  File "src/reactive_planners/demos/demo_dgh_sim_solo12_step_adjustment.py", line 313, in <module>
    [100., 100., 100.], [15., 15., 15.], [25., 25., 25.], [22.5, 22.5, 22.5]
  File "src/reactive_planners/demos/demo_dgh_sim_solo12_step_adjustment.py", line 74, in __init__
    c.initialize(self.robot.model, root_name, endeff_names[i])
RuntimeError: Caught an unknown exception!
```

Could you fix this bug? Let me know if you need more information about how did it happen?

Thanks you very much for your time and reply in advance.

Best regards

**Comment by Lhumd** [comment]
Hello,

I follow the wiki and it works on my computer. What are the OS and python version you using?

**Comment by SiyuChen1** [comment]
Hi,

I am using Ubuntu 18.04 and python 3.6 inside the anaconda environment.

Best regards

**Comment by honghongzhenbang** [comment]
Hello,
Hello, I encountered a similar error. Did you manage to resolve this issue? The error message I received is as follows:


```
TypeError: No registered converter was able to extract a C++ reference to type pinocchio::ModelTpl<double, 0, pinocchio::JointCollectionDefaultTpl> from this Python object of type Model

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/reactive_planners/demos/demo_dgh_sim_solo12_step_adjustment.py", line 312, in <module>
    centroidal_controller = CentroidalController(head, 'solo12/solo12', 0.2, 50., 0.7,
  File "src/reactive_planners/demos/demo_dgh_sim_solo12_step_adjustment.py", line 74, in __init__
    c.initialize(self.robot.model, root_name, endeff_names[i])
RuntimeError: Caught an unknown exception!
```
