### ISSUE TITLE
Error while `colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release` process

### ISSUE THREAD

**Issue by dvogureckiy99** [machines-in-motion/reactive_planners#23]
Error while `colcon build` process:
```
Traceback (most recent call last):
  File "setup.py", line 159, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 153, in run
    self._build_xacro()
  File "setup.py", line 117, in _build_xacro
    self._build_single_xacro_file(xacro_file, generated_urdf_path)
  File "setup.py", line 120, in _build_single_xacro_file
    from xacro import process_file, open_output
ModuleNotFoundError: No module named 'xacro'
```

**Comment by Lhumd** [comment]
Hi,

Can you send the full output of the colon build here and specify which OS and python you use on your system?
